export const ADD_CITY_REQUEST = "ADD_CITY_REQUEST";
export const ADD_CITY_SUCCESS = "ADD_CITY_SUCCESS";
export const ADD_CITY_FAILURE = "ADD_CITY_FAILURE";

export const GET_CITIES_REQUEST = "GET_CITIES_REQUEST";
export const GET_CITIES_SUCCESS = "GET_CITIES_SUCCESS";
export const GET_CITIES_FAILURE = "GET_CITIES_FAILURE";

export const SORT_DATA = "SORT_DATA";
export const FILTER_BY_COUNTRY = "FILTER_BY_COUNTRY";

export const GET_CITY_REQUEST = "GET_CITY_REQUEST";
export const GET_CITY_SUCCESS = "GET_CITY_SUCCESS";
export const GET_CITY_FAILURE = "GET_CITY_FAILURE";

export const DELETE_CITY_REQUEST = 'DELETE_CITY_REQUEST'
export const DELETE_CITY_SUCCESS = 'DELETE_CITY_SUCCESS'
export const DELETE_CITY_FAILURE = 'DELETE_CITY_FAILURE';

export const UPDATE_CITY_REQUEST = 'UPDATE_CITY_REQUEST'
export const UPDATE_CITY_SUCCESS = 'UPDATE_CITY_SUCCESS'
export const UPDATE_CITY_FAILURE = 'UPDATE_CITY_FAILURE';

export const ITEMS_PER_PAGE_REQUEST = 'ITEMS_PER_PAGE_REQUEST'
export const ITEMS_PER_PAGE_SUCESS = 'ITEMS_PER_PAGE_SUCESS'
export const ITEMS_PER_PAGE_FAILURE = 'ITEMS_PER_PAGE_FAILURE'

export const PAGE_CHANGE_REQUEST = 'PAGE_CHANGE_REQUEST'
export const PAGE_CHANGE_SUCCESS = 'PAGE_CHANGE_SUCCESS'
export const PAGE_CHANGE_FAILURE = 'PAGE_CHANGE_FAILURE'